---
- name: bullseye
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ bullseye_repos | difference(bullseye_repos_blacklist) }}"
  when:
  - ansible_distribution_release == 'bullseye'

- name: bookworm
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ bookworm_repos | difference(bookworm_repos_blacklist) }}"
  when:
  - ansible_distribution_release == 'bookworm'

- name: install fasttrack
  apt:
    name: fasttrack-archive-keyring
  when:
  - ansible_distribution_release == 'bullseye'

- name: bullseye fasttrack
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  loop:
  - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
  - deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib
  when:
  - ansible_distribution_release == 'bullseye'

# raspbian 32bit bullseye
# - name: all the repos
#   apt_repository:
#     repo: "{{ item }}"
#     state: present
#     update_cache: yes
#   loop:
#   - deb http://deb.debian.org/debian bullseye contrib non-free
#   - deb-src http://deb.debian.org/debian bullseye contrib non-free
#   - deb http://security.debian.org/debian-security bullseye-security contrib non-free
#   - deb-src http://security.debian.org/debian-security bullseye-security contrib non-free
#   when:
#   - ansible_distribution_release == 'bullseye'
#   - ansible_architecture == "armv7l"
