---
- name: install
  apt:
    name:
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python3-venv
    - python3-setuptools

- name: install
  apt:
    state: latest
    name: python-is-python3
  when:
  - ansible_distribution_release != 'buster'
