---
kubectl_architecture:
  x86_64: amd64
  aarch64: arm64
kubectx_architecture:
  x86_64: x86_64
  aarch64: arm64
kubecolor_architecture:
  x86_64: x86_64
  aarch64: arm64
kind_architecture:
  x86_64: amd64
  aarch64: arm64
kubeshark_architecture:
  x86_64: amd64
  aarch64: arm64
kustomize_architecture:
  x86_64: amd64
  aarch64: arm64
