---
- name: install git
  apt:
    name: git
  when: git_version == 'apt'

- name: install git
  apt:
    name: git
    default_release: "{{ansible_distribution_release}}-backports"
  when: git_version == 'backports'

- name: build git
  include_tasks: "build.yml"
  when:
  - git_version != 'apt'
  - git_version != 'backports'
  - git_version != 'none'
